version: 2
jobs:

  test-php74:
    docker:
      - image: circleci/php:7.4-cli

    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Run tests - Highest
          command: |
            composer update -n --prefer-dist --prefer-lowest
            php vendor/bin/phpunit

  test-php80:
    docker:
      - image: circleci/php:8.0-cli

    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Run tests - Highest
          command: |
            composer update -n --prefer-dist
            php vendor/bin/phpunit

workflows:
  version: 2
  test:
    jobs:
      - test-php74
      - test-php80